// Every IPC command must be explicitly granted in capabilities/default.json;
// anything not listed here cannot be invoked from the UI at all.
const COMMANDS: &[&str] = &[
    "init",
    "update_settings",
    "choose_root",
    "rescan",
    "clear_cache",
    "get_status",
    "query",
    "stats",
    "subfolders",
    "inspect",
    "preview_info",
    "read_text",
    "open_file",
    "reveal_file",
    "copy_path",
    "store_frame",
    "video_session_start",
    "ui_alive",
    "video_session_end",
    "take_recovered",
    "trash_summary",
    "trash_items",
    "rename_item",
    "analysis_locations",
    "analysis_choose_folder",
    "analysis_start",
    "analysis_cancel",
    "analysis_results",
    "analysis_clear",
    "analysis_cleanup",
    "analysis_cleanup_cancel",
    "similar_start",
    "similar_cancel",
    "similar_frames",
    "similar_results",
    "similar_dismiss",
    "similar_dismissed_count",
    "similar_forget_decisions",
    "similar_clear",
    "similar_cleanup",
    "set_folder_private",
    "file_report",
    "set_read_only",
    "set_folder_protected",
    "pdf_info",
    "archive_listing",
    "open_drive_safely",
    "set_drive_previews",
    "set_capture_override",
    "file_metadata",
    "meta_start",
    "meta_pause",
    "meta_cancel",
    "meta_clear",
    "meta_results",
    "meta_places",
    "sanitize_copies",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
